# Generated by Django 6.0.3 on 2026-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assignment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
